server:
  corednsaddr: ""
  apiconn: "api.ping.clustercat.com:443"
  apihost: ""
  apiport: "8081"
  grpcconn: "grpc.ping.clustercat.com:443"
  grpchost: ""
  grpcport: "50051"
  grpcsecure: "on"
  mqhost: "localhost"
  masterkey: "secretkey"
  dnskey: ""
  allowedorigin: "*"
  nodeid: "netmaker"
  restbackend: "on"
  agentbackend: "on"
  messagequeuebackend: "on"
  clientmode: "on"
  dnsmode: "on"
  disableremoteipcheck: ""
  grpcssl: "on"
  version: ""
  sqlconn: ""
  platform: ""
  database: "sqlite"
  defaultnodelimit: ""
  verbosity: 3
  servercheckininterval: ""
  authprovider: ""
  clientid: ""
  clientsecret: ""
  frontendurl: ""
  displaykeys: ""
  azuretenant: ""
  rce: "off"
  telemetry: ""
  manageiptables: "off"
  portforwardservices: ""
  hostnetwork: "off"
  mqport: ""
  server: "broker.ping.clustercat.com"
